### ISSUE TITLE
IMPLEMENT THE TOOLMAN

### ISSUE THREAD

**Issue by foneandrew** [hjwylde/werewolf#103]
THE TOOLMAN THROWS SPANNERS INTO SHIT
LIKE FOR AN EXAMPLE OR WHATEVER:
THE WITCHY-POO MIGHT BE ABOUT TO GUZZLE A DIRTY POTION OR SOMETHANG
AND THEN FROM OUDA NOWHERES, THE TOOLMAN THROWS A SPANNER INTO THE WORKS, AND THE WITCHY-POOS DRINKS A DIFFERENT POTION. THE TOOLMAN IS POOR AS FUCKTHOUGH SO CAN ONLY THROUGH 2 AAND QUARTER SPANNERS. THE QUARTER SPANNER IS ACTUALLY A SPOON AND DOES NOTHING. BUT IT SAYS THAT THE TOOLMAN THROWED A SPOON, AND THE WHOLE CHANNEL GIVES THEM SHIT FOR BEING A DUMBASS

TO THROWS THE SPANNERS THE TOOLMAN JUST CHOOSES A PERSON TO THROW A SPANNER AT. THEY DONT KNOW WHATS GOING ON THOUGH, THEY NEED TO USE THEIR FEARSOMNE POWERS OF DEDCUTION TO FIGURE OUT WHO THEY SHOULD THROWS A SPANNERS AT.

IF THEY END UP THROWING A SPANNERS AT A WEREDIDDLER THEN IT JUST GETS LIKE REAL FUCKED OFF AND STUFF, AND DIDDLES THE TOOLMAN INSTEAD OF THEIR ORIGINAL TARGET.

THIS ROLE IS FULLY ENDORSED BY PETA

**Comment by hjwylde** [comment]
Thanks Andy, I will consider this while the issue is in the closed state.
