### ISSUE TITLE
MAKE MARTY MCFLY A HAPPENING THING

### ISSUE THREAD

**Issue by foneandrew** [hjwylde/werewolf#104]
MARTYMCFLY IS A ROLE FOR THE HIT GAME WEREDIDDLERS.

MARTYMCFLY CAN TRAVEL IN TIME, BUT ONLY HAS ENOUGH GARBAGE TO GO BACK IN TIME ONCE IN HIS TIMETRAVELING MINIVAN. 

AT THE VERY START OF EACH ROUND, MUZZLE MCDAGS CAN CHOOSE TO BACK IN TIME TO THE START OF THE LAST ROUND, TO CHANGE HOW THEY VOTED. THE OTHER PLAYERS CANNOT CHANGE WHO THEY VOTED FOR, OR WHAT THEY DID. THAT SHIT IS ALL WELL LOCKED IN. BUT THE MCFLAG CAN CHANGE WHO THEY VOTE TO LYNCH, POTENTIALLY REVERSING A POOS SITUATION, OR SWAYING A VOTE TO LYNCH A DIDDLER.

AMRTY THE FLY IS A MORTAL THOUGH SO CANNOT GO BACK IN TIME ONCE THEY'VE BEEN DIDDLED.

MARTY MCFLU IS A LOCAL HERO AND SHOUILD BE IN THE GAME UNLESS YOU HATE ORPAHNS

**Comment by hjwylde** [comment]
Thanks Andy, I will consider this while the issue is in the closed state.

**Comment by EilisByrne** [comment]
i THNiK THS iZ A GRAPE ROLE.  iMPLEMENT NAOW!!!
