### ISSUE TITLE
Implement the Oracle

### ISSUE THREAD

**Issue by hjwylde** [hjwylde/werewolf#141]
The Oracle may once a night, determine the role of one player.

**Comment by davismatt1** [comment]
Lore: Originally rejected by the townsfolk, the Oracle's accurate prophetic predictions has earned trust within the village. With constant precognition of the town, the Oracle is only interested with the future - and knows the village will only live if they work together. Each night the Oracle will accurately predict the exact role of one player of their choice. This wisdom is for the Oracle to use to ensure the future of Fougères.

**Comment by hjwylde** [comment]
+1 thank you !!
