### ISSUE TITLE
Add a translation file

### ISSUE THREAD

**Issue by foneandrew** [hjwylde/werewolf#155]
This would make it possible to change the phrases / names of roles dynamically.

**Comment by hjwylde** [comment]
For parsing translation files: https://hackage.haskell.org/package/pandoc

This can also parse emojis to unicode code points.

**Comment by hjwylde** [comment]
https://hackage.haskell.org/package/shakespeare
http://www.yesodweb.com/book/shakespearean-templates

**Comment by hjwylde** [comment]
Write the message structure in terms of events. (Either successful, or an error code.)
