### ISSUE TITLE
Dead players shouldn't keep getting messages

### ISSUE THREAD

**Issue by tigerwnz** [hjwylde/werewolf#24]

**Comment by hjwylde** [comment]
+1

**Comment by hjwylde** [comment]
What message had you received?

**Comment by tigerwnz** [comment]
```[werewolf] voted to kill [villager]```

(I was a werewolf, but had long since been killed)

**Comment by hjwylde** [comment]
Fixed in v0.2.0.2, v0.3.0.4 and v0.3.1.2.
