### ISSUE TITLE
Is seer broke?

### ISSUE THREAD

**Issue by MrKhoaBean** [hjwylde/werewolf#263]
![image](https://user-images.githubusercontent.com/46867018/90279867-d4468d00-de1e-11ea-8ab4-aa1814b9e0f0.png)
i don't know why it don't have message for @grault

**Comment by hjwylde** [comment]
Hi @MrKhoaBean, the seer shouldn't be broken, I believe after #184 the seer is only told the allegiance after sunrise. (I'm afraid the screenshot in the README is a little out of date.)
