### ISSUE TITLE
Is there any linux/macOS executable?

### ISSUE THREAD

**Issue by khoakomlem** [hjwylde/werewolf#264]
On window, I run "stack install werewolf" and it create .exe file for me, so how about linux/macOS?

**Comment by hjwylde** [comment]
Hi,

`stack install` should create the binaries no matter the OS. If you're having trouble finding the binaries that it builds, see https://stackoverflow.com/questions/51352885/how-do-you-set-the-executable-output-location-for-a-haskell-project-built-with-s - it's possible to customize where the binaries are created. Hope that helps!
