### ISSUE TITLE
Better death messages

### ISSUE THREAD

**Issue by kuahyeow** [hjwylde/werewolf#28]
> the distinguished hjwylde was found prostrated against the doorstep with a note stuck to his back, "apostropheeees"

> hjwylde croaks, "I am died"

> with his last breath, he still grammar'ed badly

> we find brain matter splattered on the door, and the lifeless body of hjwylde next to it

> the guts of some poor villager (hjwylde)

> hjwylde tries to stuff their colon back vainly

**Comment by hjwylde** [comment]
Happy to change / improve messages on a per message basis. Closing this as there's nothing specific to do right now.

Grammar will be handled in #72 :).
