### ISSUE TITLE
Zombie scapegoat!

### ISSUE THREAD

**Issue by binary-koan** [hjwylde/werewolf#85]
(May be a duplicate of a previous issue)

If the villagers' vote is tied twice then the message about the scapegoat dying is reported both times. It doesn't seem to cause any problems in the game, but is confusing.

**Comment by hjwylde** [comment]
I accidentally saw that a few days ago in the code :P. It's fixed in #20 or
master I think. Will confirm.

**Comment by hjwylde** [comment]
Fixed in #62 (released v0.4.6.0).
