### ISSUE TITLE
Implement the Medusa

### ISSUE THREAD

**Issue by hjwylde** [hjwylde/werewolf#99]
If the Medusa is devoured, they're eliminated, but the first Werewolf to their left is turned to stone.

**Comment by hjwylde** [comment]
Rename to the Medusa.

**Comment by davismatt1** [comment]
Lore: A beautiful woman, Medusa is aligned with the villagers but harbours a terrifying secret. During the day she is well known in the village of Fougères for her stunning appearance which captures the eye and love of all the town-folk. However her terrifying secret takes hold when the sun goes down and her true self is revealed. This is in the form of live snakes for hair and anyone who gazes upon her eyes turn to stone. If Medusa attracts the attention of a Werewolf during the night, as she is devoured the Werewolf to her left will catch her gaze and turn to stone, instantly killing the lupine predator.

**Comment by hjwylde** [comment]
Perfect +1 - Thank you heaps!
